// Generated by gencpp from file skeleton_detection/skeleton_message.msg
// DO NOT EDIT!


#ifndef SKELETON_DETECTION_MESSAGE_SKELETON_MESSAGE_H
#define SKELETON_DETECTION_MESSAGE_SKELETON_MESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <skeleton_detection/joint_message.h>

namespace skeleton_detection
{
template <class ContainerAllocator>
struct skeleton_message_
{
  typedef skeleton_message_<ContainerAllocator> Type;

  skeleton_message_()
    : header()
    , userID(0)
    , uuid()
    , joints()
    , time()  {
    }
  skeleton_message_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , userID(0)
    , uuid(_alloc)
    , joints(_alloc)
    , time()  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _userID_type;
  _userID_type userID;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _uuid_type;
  _uuid_type uuid;

   typedef std::vector< ::skeleton_detection::joint_message_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::skeleton_detection::joint_message_<ContainerAllocator> >::other >  _joints_type;
  _joints_type joints;

   typedef ros::Time _time_type;
  _time_type time;




  typedef boost::shared_ptr< ::skeleton_detection::skeleton_message_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::skeleton_detection::skeleton_message_<ContainerAllocator> const> ConstPtr;

}; // struct skeleton_message_

typedef ::skeleton_detection::skeleton_message_<std::allocator<void> > skeleton_message;

typedef boost::shared_ptr< ::skeleton_detection::skeleton_message > skeleton_messagePtr;
typedef boost::shared_ptr< ::skeleton_detection::skeleton_message const> skeleton_messageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::skeleton_detection::skeleton_message_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::skeleton_detection::skeleton_message_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace skeleton_detection

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'skeleton_detection': ['/home/howe/turtlebot_demo/src/skeleton_detection/skeleton_detection/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::skeleton_detection::skeleton_message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::skeleton_detection::skeleton_message_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::skeleton_detection::skeleton_message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::skeleton_detection::skeleton_message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::skeleton_detection::skeleton_message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::skeleton_detection::skeleton_message_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::skeleton_detection::skeleton_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "589c3bd97c29fc2a814e315fab41f168";
  }

  static const char* value(const ::skeleton_detection::skeleton_message_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x589c3bd97c29fc2aULL;
  static const uint64_t static_value2 = 0x814e315fab41f168ULL;
};

template<class ContainerAllocator>
struct DataType< ::skeleton_detection::skeleton_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "skeleton_detection/skeleton_message";
  }

  static const char* value(const ::skeleton_detection::skeleton_message_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::skeleton_detection::skeleton_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32 userID\n\
string uuid\n\
skeleton_detection/joint_message[] joints\n\
time time\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: skeleton_detection/joint_message\n\
string name\n\
geometry_msgs/Pose pose\n\
float32 confidence\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::skeleton_detection::skeleton_message_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::skeleton_detection::skeleton_message_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.userID);
      stream.next(m.uuid);
      stream.next(m.joints);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct skeleton_message_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::skeleton_detection::skeleton_message_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::skeleton_detection::skeleton_message_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "userID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.userID);
    s << indent << "uuid: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.uuid);
    s << indent << "joints[]" << std::endl;
    for (size_t i = 0; i < v.joints.size(); ++i)
    {
      s << indent << "  joints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::skeleton_detection::joint_message_<ContainerAllocator> >::stream(s, indent + "    ", v.joints[i]);
    }
    s << indent << "time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SKELETON_DETECTION_MESSAGE_SKELETON_MESSAGE_H
